### ISSUE TITLE
Don't change the indentation of secrets

### ISSUE THREAD

**Issue by Xcalizorz** [sniptt-official/ots#17]
Thanks for the interesting tool!

I want to store `yaml` and `json` data exactly as they are without changes to their indentation:

```json
{
  "foo": "bar"
}
```

Indentation in `json` is not very important, but can become ugly when the `json` data is larger. 

```yaml
version: v1alpha1
metadata:
  name: secret-data
spec:
  data:
    - hello world
``` 

## Expected

The expected outcome is that I get the same data back, without change in indentations. Especially `yaml` should stay exactly the same because the syntax depends on indentation.

## Actual result

```json
{
"foo": "baar"
}
```

```yaml
version: v1alpha1
metadata:
name: secret-data
spec:
data:
- hello world
```

It might be that the fault lies in the underlying encryption package.
